server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: []

logging:
  appenders:
    - type: console
      logFormat: "- %-5p  %m [%c{60}]%n"
  level: INFO

appTitle: "Dropwizard sample"